script:
- sudo apt-get update
- sudo apt-get install --no-install-recommends texlive-fonts-recommended texlive-extra-utils texlive-latex-extra texlive-fonts-extra texlive-latex-recommended pandoc
- make dist
