language: r
pandoc_version: 2.1.2
group: travis_latest

addons:
  apt:
    packages:
      - texlive-fonts-recommended
      - texlive-extra-utils
      - texlive-latex-extra
      - texlive-fonts-extra
      - texlive-latex-recommended

before_install:
- sudo apt-get update
- tlmgr install texfot

script:
- make dist

